name: Build CI Docker Images
on:
  push:
    paths:
      - ci-builder/**

jobs:
  build:
    name: Docker build with ${{ matrix.config.compiler }} and Boost ${{ matrix.config.boost }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [
          {compiler: g++-4.9, boost: 1.61.0},
          {compiler: g++-8, boost: 1.65.0},
          {compiler: clang-3.6, boost: 1.58.0},
          {compiler: clang-8, boost: 1.65.0},
        ]
 
    steps:
    - uses: actions/checkout@v1
    #-name: Login to Docker Hub
    # run: docker login
    - uses: azure/container-actions/docker-login@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push the Docker image
      env:
        COMPILER: ${{ matrix.config.compiler }}
        BOOST_VERSION: ${{ matrix.config.boost }}
      run: |
        echo Building Docker image with $COMPILER and Boost $BOOST_VERSION
        docker build . --file ci-builder/Dockerfile --tag helics/buildenv:${COMPILER/g++/gcc}_boost-${BOOST_VERSION} --build-arg COMPILER=${COMPILER} --build-arg BOOST_VERSION=${BOOST_VERSION}
        docker push helics/buildenv:${COMPILER/g++/gcc}_boost-${BOOST_VERSION}
