name: Docker Image CI

on: [push]

jobs:
  build:
    name: Docker build with ${{ matrix.config.compiler }} and Boost ${{ matrix.config.boost }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [{compiler: g++-4.9, boost: 1.61.0}, {compiler: g++-8, boost: 1.65.0}, {compiler: clang-3.6, boost: 1.58.0}, {compiler: clang-8, boost: 1.65.0}]
        #include:
        #  - compiler: g++-4.9
        #    boost_version: 1.61.0
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        BOOST_VERSION: ${{ matrix.config.boost }}
      run: |
        echo Using $BOOST_VERSION
      #docker build . --file Dockerfile --tag my-image-name:$(date +%s)
