name: Update Docker Images
on:
  push:
    paths:
      - '**/Dockerfile'
      - '!ci-builder/**'

jobs:
  build:
    name: Build changed Dockerfiles
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - uses: azure/container-actions/docker-login@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push updated Docker containers
      run: .github/workflows/scripts/build-changed-dockerfiles.sh "${{ github.sha }}"
